const KEYS={pets:'pets',reminders:'petReminders',care:'petCareRecords',profile:'petBuddyProfile',settings:'petSettings',messages:'contactMessages'};
const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const emoji=t=>({Dog:'🐶',Cat:'🐱',Rabbit:'🐰',Bird:'🐦',Other:'🐾'}[t]||'🐾');
function toast(msg){let el=document.getElementById('toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function nav(active){return `<header><a class="logo" href="index.html"><span class="logo-icon">🐾</span>Pet Care Buddy</a><nav class="nav"><a class="${active==='home'?'active':''}" href="index.html">Home</a><a class="${active==='dashboard'?'active':''}" href="dashboard.html">Dashboard</a><a class="${active==='pets'?'active':''}" href="my-pet.html">My Pets</a><a class="${active==='care'?'active':''}" href="care.html">Care</a><a class="${active==='reminders'?'active':''}" href="reminders.html">Reminders</a><a class="${active==='about'?'active':''}" href="about.html">About</a><a class="${active==='contact'?'active':''}" href="contact.html">Contact</a><a class="${active==='settings'?'active':''}" href="settings.html">Settings</a></nav></header>`}
function footer(){return `<footer>© 2026 Pet Care Buddy · Made with care for pets 🐾</footer>`}
function petList(){return read(KEYS.pets,[])}
function petById(id){return petList().find(p=>p.id===id)}
function openModal(id){document.getElementById(id)?.classList.add('show')}
function closeModal(id){document.getElementById(id)?.classList.remove('show')}
function petFormHtml(p={}){return `<form id="petForm"><input type="hidden" id="petId" value="${esc(p.id||'')}"><label>Pet name</label><input class="input" id="petNameInput" value="${esc(p.name||'')}" required placeholder="e.g. Bruno"><label>Pet type</label><select id="petType" required><option value="">Select type</option>${['Dog','Cat','Rabbit','Bird','Other'].map(x=>`<option ${p.type===x?'selected':''}>${x}</option>`).join('')}</select><label>Breed</label><input class="input" id="petBreed" value="${esc(p.breed||'')}" placeholder="e.g. Labrador"><div class="grid grid-2"><div><label>Age (years)</label><input class="input" id="petAge" type="number" min="0" max="100" step="0.1" value="${esc(p.age??'')}" required></div><div><label>Gender</label><select id="petGender" required><option value="">Select</option><option ${p.gender==='Male'?'selected':''}>Male</option><option ${p.gender==='Female'?'selected':''}>Female</option></select></div></div><label>Notes</label><textarea class="input" id="petNotes" rows="3" placeholder="Allergies, habits, special care...">${esc(p.notes||'')}</textarea><div class="actions"><button class="primary" type="submit">Save Pet</button><button class="secondary" type="button" onclick="closeModal('petModal')">Cancel</button></div></form>`}
function savePetFromForm(e){e.preventDefault();const f=e.target,id=document.getElementById('petId').value;let pets=petList();const p={id:id||crypto.randomUUID(),name:document.getElementById('petNameInput').value.trim(),type:document.getElementById('petType').value,breed:document.getElementById('petBreed').value.trim(),age:document.getElementById('petAge').value,gender:document.getElementById('petGender').value,notes:document.getElementById('petNotes').value.trim()};if(!p.name||!p.type||!p.age||!p.gender)return toast('Please fill all required details.');if(id){pets=pets.map(x=>x.id===id?{...x,...p}:x)}else pets.push(p);write(KEYS.pets,pets);closeModal('petModal');renderPets();toast(id?'Pet updated':'Pet added successfully')}
function renderPets(){const c=document.getElementById('pets');if(!c)return;const pets=petList();c.innerHTML=pets.length?pets.map(p=>`<article class="card"><div class="pet-photo">${emoji(p.type)}</div><h2>${esc(p.name)}</h2><p class="muted">${esc(p.breed||p.type)} · ${esc(p.age)} ${Number(p.age)===1?'year':'years'} · ${esc(p.gender)}</p><div class="actions"><button class="primary" onclick="viewPet('${p.id}')">View Profile</button><button class="secondary" onclick="editPet('${p.id}')">Edit</button><button class="danger" onclick="deletePet('${p.id}')">Delete</button></div></article>`).join(''):`<div class="empty"><span class="big">🐶</span><h2>No pets added yet</h2><p>Add your first pet to start managing their care.</p><button class="primary" onclick="openAddPet()">+ Add Your Pet</button></div>`}
function openAddPet(){document.getElementById('petModalContent').innerHTML=petFormHtml();openModal('petModal');document.getElementById('petForm').onsubmit=savePetFromForm}
function editPet(id){document.getElementById('petModalContent').innerHTML=petFormHtml(petById(id));openModal('petModal');document.getElementById('petForm').onsubmit=savePetFromForm}
function deletePet(id){if(!confirm('Delete this pet and its care records?'))return;write(KEYS.pets,petList().filter(p=>p.id!==id));write(KEYS.care,read(KEYS.care).filter(r=>r.petId!==id));write(KEYS.reminders,read(KEYS.reminders).filter(r=>r.petId!==id));renderPets();toast('Pet deleted')}
function viewPet(id){location.href=`profile.html?id=${encodeURIComponent(id)}`}
function careFormHtml(r={}){const pets=petList();return `<form id="careForm"><input type="hidden" id="careId" value="${esc(r.id||'')}"><label>Pet</label><select id="carePet" required><option value="">Select pet</option>${pets.map(p=>`<option value="${esc(p.id)}" ${r.petId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><label>Record type</label><select id="careType" required>${['Vaccination','Medicine','Feeding','Vet Visit','Health Note'].map(x=>`<option ${r.type===x?'selected':''}>${x}</option>`).join('')}</select><label>Title</label><input class="input" id="careTitle" value="${esc(r.title||'')}" required placeholder="e.g. Rabies vaccine"><label>Date</label><input class="input" id="careDate" type="date" value="${esc(r.date||new Date().toISOString().slice(0,10))}" required><label>Notes</label><textarea class="input" id="careNotes" rows="4" placeholder="Dosage, vet notes, feeding details...">${esc(r.notes||'')}</textarea><div class="actions"><button class="primary" type="submit">Save Record</button><button class="secondary" type="button" onclick="closeModal('careModal')">Cancel</button></div></form>`}
function saveCare(e){e.preventDefault();const id=document.getElementById('careId').value;let records=read(KEYS.care);const r={id:id||crypto.randomUUID(),petId:document.getElementById('carePet').value,type:document.getElementById('careType').value,title:document.getElementById('careTitle').value.trim(),date:document.getElementById('careDate').value,notes:document.getElementById('careNotes').value.trim()};if(!r.petId||!r.title||!r.date)return toast('Please complete the record.');records=id?records.map(x=>x.id===id?r:x):[...records,r];write(KEYS.care,records);closeModal('careModal');renderCare();toast(id?'Record updated':'Care record saved')}
function renderCare(){const c=document.getElementById('careRecords');if(!c)return;const records=read(KEYS.care).sort((a,b)=>b.date.localeCompare(a.date));c.innerHTML=records.length?records.map(r=>{const p=petById(r.petId);return `<article class="card record"><div class="record-main"><div class="record-icon">${({Vaccination:'💉',Medicine:'💊',Feeding:'🍖','Vet Visit':'🩺','Health Note':'📋'})[r.type]||'🐾'}</div><div><h3>${esc(r.title)}</h3><p class="muted">${esc(p?.name||'Unknown pet')} · ${esc(r.type)} · ${new Date(r.date+'T00:00').toLocaleDateString('en-IN')}</p>${r.notes?`<p class="muted">${esc(r.notes)}</p>`:''}</div></div><div class="actions"><button class="secondary" onclick="editCare('${r.id}')">Edit</button><button class="danger" onclick="deleteCare('${r.id}')">Delete</button></div></article>`}).join(''):`<div class="empty"><span class="big">🩺</span><h2>No care records yet</h2><p>Add vaccinations, medicines, feeding logs, vet visits or health notes.</p></div>`}
function openAddCare(){if(!petList().length)return toast('Add a pet first.');document.getElementById('careModalContent').innerHTML=careFormHtml();openModal('careModal');document.getElementById('careForm').onsubmit=saveCare}
function editCare(id){document.getElementById('careModalContent').innerHTML=careFormHtml(read(KEYS.care).find(r=>r.id===id));openModal('careModal');document.getElementById('careForm').onsubmit=saveCare}
function deleteCare(id){if(!confirm('Delete this care record?'))return;write(KEYS.care,read(KEYS.care).filter(r=>r.id!==id));renderCare();toast('Record deleted')}
function reminderFormHtml(r={}){return `<form id="reminderForm"><input type="hidden" id="reminderId" value="${esc(r.id||'')}"><label>Pet</label><select id="reminderPet"><option value="">No specific pet</option>${petList().map(p=>`<option value="${esc(p.id)}" ${r.petId===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><label>Reminder title</label><input class="input" id="reminderTitle" value="${esc(r.title||'')}" required placeholder="e.g. Vaccination due"><label>Type</label><select id="reminderType"><option>Vaccination</option><option>Medicine</option><option>Vet Visit</option><option>Feeding</option><option>Other Care</option></select><label>Date</label><input class="input" id="reminderDate" type="date" value="${esc(r.date||'')}" required><label>Time</label><input class="input" id="reminderTime" type="time" value="${esc(r.time||'')}"><div class="actions"><button class="primary" type="submit">Save Reminder</button><button class="secondary" type="button" onclick="closeModal('reminderModal')">Cancel</button></div></form>`}
function saveReminder(e){e.preventDefault();const id=document.getElementById('reminderId').value;let rs=read(KEYS.reminders);const r={id:id||crypto.randomUUID(),petId:document.getElementById('reminderPet').value,title:document.getElementById('reminderTitle').value.trim(),type:document.getElementById('reminderType').value,date:document.getElementById('reminderDate').value,time:document.getElementById('reminderTime').value,completed:false};if(id){const old=rs.find(x=>x.id===id);r.completed=old?.completed||false}if(!r.title||!r.date)return toast('Please add a title and date.');rs=id?rs.map(x=>x.id===id?r:x):[...rs,r];write(KEYS.reminders,rs);closeModal('reminderModal');renderReminders();toast(id?'Reminder updated':'Reminder added')}
function renderReminders(){const c=document.getElementById('reminders');if(!c)return;let rs=read(KEYS.reminders).sort((a,b)=>(a.date+(a.time||'')).localeCompare(b.date+(b.time||'')));c.innerHTML=rs.length?rs.map((r,i)=>{const p=petById(r.petId);return `<article class="card record ${r.completed?'muted':''}"><div class="record-main"><div class="record-icon">${({Vaccination:'💉',Medicine:'💊','Vet Visit':'🩺',Feeding:'🍖','Other Care':'🐾'})[r.type]||'🔔'}</div><div><h3>${esc(r.title)}</h3><p class="muted">${esc(p?.name||'All pets')} · ${new Date(r.date+'T00:00').toLocaleDateString('en-IN')}${r.time?' · '+esc(r.time):''}</p></div></div><div class="actions"><button class="secondary" onclick="toggleReminder('${r.id}')">${r.completed?'Undo':'Complete'}</button><button class="secondary" onclick="editReminder('${r.id}')">Edit</button><button class="danger" onclick="deleteReminder('${r.id}')">Delete</button></div></article>`}).join(''):`<div class="empty"><span class="big">🔔</span><h2>No reminders yet</h2><p>Add vaccination, medicine, vet or feeding reminders.</p></div>`}
function openAddReminder(){document.getElementById('reminderModalContent').innerHTML=reminderFormHtml();openModal('reminderModal');document.getElementById('reminderForm').onsubmit=saveReminder}
function editReminder(id){document.getElementById('reminderModalContent').innerHTML=reminderFormHtml(read(KEYS.reminders).find(r=>r.id===id));openModal('reminderModal');document.getElementById('reminderForm').onsubmit=saveReminder}
function toggleReminder(id){write(KEYS.reminders,read(KEYS.reminders).map(r=>r.id===id?{...r,completed:!r.completed}:r));renderReminders()}
function deleteReminder(id){if(!confirm('Delete this reminder?'))return;write(KEYS.reminders,read(KEYS.reminders).filter(r=>r.id!==id));renderReminders();toast('Reminder deleted')}
